name : Build success on PR

on : 
   pull_request: 
      branches:
         - master

jobs: 
    build: 
      name: build the project 
      runs-on: ubuntu-latest
      setps: 
          - uses: actions/checkout@v3
          - name: Use Nodes.js
            uses: actions/setup-node@v3
            with: 
              node-version: '20'

          - name: Install Dependencies
            run: npm install

          - name: Generate Prisma Client
            run: npm run db:generate

          - name: Run Build
            npm run build     
